modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Creators-of-Create/Create/issues"
license="MIT"

[[mods]]
modId="create"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime 
version="${file.jarVersion}"
displayName="Create"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create"
logoFile="logo.png"
#credits=""
authors="simibubi"
description='''
Technology that empowers the player.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.110,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.5,0.6.6)"
    ordering="AFTER"
    side="CLIENT"
